DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM0NDM3MTY0LCJ1c2VySWQiOjJ9.RjF8_LiFHuIJIIHezVrPnrYsX5X1axxKSNNxMH324z8